### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by ice-phoenix** [SidorenkoNikita/Floating_Point#1]
* В задании имелось в виду число с физической размерностью, т.е. `5 метров в секунду`
* `camelCase`
* `public` поля --- это очень плохая идея
* Нет ли более простого способа сделать из мантиссы строку, чем `a.toString().substring(0, a.toString().indexOf("E"))`?
* ...

**Comment by SidorenkoNikita** [comment]
... - это что значит?

**Comment by SidorenkoNikita** [comment]
Я правильно понимаю, что требуется перевод, если размерности одинакового типа?
Например, У нас есть метры в секунду и километры в минуту. Мы производим перевод из одной размерности в другую, предварительно огласив, в какую именно.
